### PR TITLE
Python 3.7+ compat

### PR DESCRIPTION
**Pull request by AdilZouitine**
Hi again :smile: , 

You will find in this pull request some modifications in the code and tests to make them compatible with python 3.7 +.
My code is available at the code review.

However, versions 3.7 and 3.8 in the CI are missing (I tested in local on python 3.7 and 3.9).

### CODE REVIEW

**Comment by patrick-kidger** [comment]
Looks good to me.

If you could add 3.7 and 3.8 to the CI that would be good -- it should just be a matter of adding them to the matrix here:

https://github.com/patrick-kidger/torchtyping/blob/cf13bcd4f93da34ad9b6805d69bcb8f7657e25dd/.github/workflows/ci.yaml#L32

Also, could you modify the `setup.py` to:
- Include a dependency on `typing_extensions`. This should be something like `install_requires=[..., "typing_extensions==3.7.4.3;python_version<'3.9'"]`, though I've not tested that.
- Bump the version number to 0.1.1! I think this deserves a new release on PyPI.

**Comment by AdilZouitine** [comment]
Commits coming soon, before bump 0.1.1 on PyPI can you run test with github workflow ? :smile:

**Comment by AdilZouitine** [comment]
:tada:

**Comment by patrick-kidger** [comment]
Can you bump the version number here:

https://github.com/patrick-kidger/torchtyping/blob/cf13bcd4f93da34ad9b6805d69bcb8f7657e25dd/torchtyping/__init__.py#L13

to 0.1.1 please?

Also, do you have a Twitter handle? I'll make a post about this, and would be happy to credit you.

**Comment by AdilZouitine** [comment]
> Can you bump the version number here:
> 
> https://github.com/patrick-kidger/torchtyping/blob/cf13bcd4f93da34ad9b6805d69bcb8f7657e25dd/torchtyping/__init__.py#L13
> 
> to 0.1.1 please?
> 
> Also, do you have a Twitter handle? I'll make a post about this, and would be happy to credit you.

Yes my Twitter is https://twitter.com/AdilZtn  thanks you ! :smile:

**Pull request merged**
